### ISSUE TITLE
Add multiple sensors to CCI DA Reader

### ISSUE THREAD

**Issue by TimLahmers** [NASA-LIS/LISF#1134]
The ESACCI reader presently only supports the COMBINED Dataset. This proposed update will add an additional setting to the lvt.config and lis.config file to permit the CCI reader to support multiple sensor datasets ("PASSIVE", "ACTIVE", and "COMBINED").

@TimLahmers @sujayvkumar @KathyNie Pang Liu

https://github.com/NASA-LIS/LISF/labels/enhancement

**Comment by cmclaug2** [comment]
This issue was resolved by PR #1136
