### ISSUE TITLE
Add new river routing model (RAPID)

### ISSUE THREAD

**Issue by yyoon4** [NASA-LIS/LISF#1227]
Add a new river routing model, **RAPID** (Routing Application for Parallel Computation of Discharge). 

**Brief Model description**
Given surface and groundwater inflow to rivers, RAPID can compute the flow and volume of water everywhere in river networks made out of many thousands of reaches (vector-base river model). The design of RAPID allows it to be adapted to any river network if given basic connectivity information. RAPID uses a matrix version of the Muskingum method and has an automated parameter estimation procedure that allows finding optimal model parameters based on available gauge measurements.

See below the representative paper for the detailed information
David, Cédric H., David R. Maidment, Guo-Yue Niu, Zong- Liang Yang, Florence Habets and Victor Eijkhout (2011), River network routing on the NHDPlus dataset, Journal of Hydrometeorology, 12(5), 913-934. DOI: 10.1175/2011JHM1345.1 
http://rapid-hub.org/index.html

**Run environment setting**
RAPID needs the PETSc library to run. Currently, PETSc 3.16.1 is installed, which is only compatible with **intel_2021.4.0**.
Also, to run RAPID, at least, 7.5GB memory allocation per core is needed. Please make sure to set your slurm script.

**The proposed setting for LIS compilation:**
1. use 'lisf_7_intel_2021.4.0_petsc' in env/discover
2. add 'RAPID router: On' to lis/make/user.cfg 
3. select 1 during the './configure' step (i.e., Use PETSc? (1-yes, 0-no, default=0): 1)

**example for slurm setting**
...
#SBATCH --constraint=sky
#SBATCH --nodes=16 --ntasks=256 --ntasks-per-node=16
...

**Testcase**
/discover/nobackup/yyoon4/lis7/Testcase/rapid_noah39

**Comment by cmclaug2** [comment]
RAPID was added in #1228
