### ISSUE TITLE
Need to add "micromet" option to LIS met forcing readers

### ISSUE THREAD

**Issue by karsenau** [NASA-LIS/LISF#1264]
LIS met forcing readers with terrain maps need to be updated to account for the addition of MicroMet topographic downscaling routines

@karsenau

**Comment by karsenau** [comment]
Several metforcing readers have coded “ .ne. ‘none’ “ for “met_ecor” option (set in the lis.config file) when activating elevation correction to forcing fields, i.e.,:
       if( LIS_rc%met_ecor(findex).ne."none" ) then
 
The readers that currently have that as the option include:
 
Princeton forcing reader
NAM-242 forcing reader
WRFoutv2 reader
WRFAKdom reader
GFS
ERA5
ECMWF
NLDAS2

**Comment by cmclaug2** [comment]
This issue was addressed in #1265
