### ISSUE TITLE
Some HYMAP2 arrays are not deallocated

### ISSUE THREAD

**Issue by dmocko** [NASA-LIS/LISF#1291]
### Bug Description

Some of the allocated arrays in the HYMAP2 router code are not deallocated.

The good news is that this does not appear to cause an issue in running the code now.

However, to prevent possible future issues, these deallocate statements should be added.

I already have a fix ready to go, and can submit a pull request as needed.

@jvgeiger - should this go into the master branch, or one of the support branches?

**Comment by jvgeiger** [comment]
If this issue exists in the support/lisf-public-7.4 branch, then I suggest adding this fix there.

**Comment by cmclaug2** [comment]
Resolved by #1293
