### ISSUE TITLE
SMOS NRT DA, issue in grid finding period

### ISSUE THREAD

**Issue by LIS-navari** [NASA-LIS/LISF#1301]
### Bug Description
Yonghwan Kwon previously reported SMOS data are missing in large areas over the north-western CONUS where most ISMN stations are located. This issue was attributed to the hard-coded “grid finding period” in LDT. The “grid finding period” was originally (and tentatively) set to 30 days, but it seems that this period was not enough to assign all SMOS grids to the LIS grids. Yonghwan Kwon tested longer periods and the results are shown in the link below:

[https://nasa-my.sharepoint.com/:p:/g/personal/svkumar_ndc_nasa_gov/Ec-jgSEoQbBDpMdrW3Xrc0gBm_-1R9H_EVq1Jy3hXl1NTA?e=qXgje0](https://gcc02.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fnasa-my.sharepoint.com%2F%3Ap%3A%2Fg%2Fpersonal%2Fsvkumar_ndc_nasa_gov%2FEc-jgSEoQbBDpMdrW3Xrc0gBm_-1R9H_EVq1Jy3hXl1NTA%3Fe%3DqXgje0&data=05%7C01%7Cmahdi.navari%40nasa.gov%7Cd3ed2b0d01cc4dadc39f08db2e73c78a%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638154847074297287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NiJYxA381k7HL3A45l%2Bym%2FZdB0%2BbjWyJfLgD6D3JSmw%3D&reserved=0)

   
When the 150-day period was used for “grid finding” in LDT, the SMOS data (unscaled; before model-based QC) could cover the whole CONUS domain.

![Screen Shot 2023-04-03 at 11 50 46 AM](https://user-images.githubusercontent.com/43690895/229562029-b2af9f3c-1457-4642-b103-5b5c565dd3e6.png)

### Steps to Replicate
I do not have a test case for this issue. I can create a test case if needed. But, he confirmed that he did not fix the bug in the code prior to his departure. 

See the following email exchange 
Hi Mahdi,
Yes. You are right. 
Thanks,
Yonghwan

From: "Navari, Mahdi (GSFC-617.0)[UNIV OF MARYLAND COLLEGE PARK]" <[mahdi.navari@nasa.gov](mailto:mahdi.navari@nasa.gov)>
Date: Friday, March 24, 2023 at 12:20 PM
To: LIS-557WW <[LIS-557WW@nasa.onmicrosoft.com](mailto:LIS-557WW@nasa.onmicrosoft.com)>, Yonghwan Kwon <[yhkwon@umd.edu](mailto:yhkwon@umd.edu)>
Subject: Re: [update] SMOS DA

 
Hi Yonghwan,
We were discussing the SMOS NRT DA and I just remembered an old conversation between us (see previous emails below).
Do we need to change the “grid finding period” from 30 days to 150 days?

[https://github.com/NASA-LIS/LISF/blob/48a8c51aa15c49031be45342ed8b441cc27e18c0/ldt/DAobs/SMOS_NRTNN_L2sm/readSMOSNRTNNL2smObs.F90#L281](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-LIS%2FLISF%2Fblob%2F48a8c51aa15c49031be45342ed8b441cc27e18c0%2Fldt%2FDAobs%2FSMOS_NRTNN_L2sm%2FreadSMOSNRTNNL2smObs.F90%23L281&data=05%7C01%7Cmahdi.navari%40nasa.gov%7Cd3ed2b0d01cc4dadc39f08db2e73c78a%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638154847074297287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0Co3lz5wXl2OgFTuvDPnhd8AWGX4a2ReIQn7h78Ie%2FM%3D&reserved=0)

If that is the case, is this the right and only places we need to change?

Thanks
Mahdi

**Comment by cmclaug2** [comment]
Resolved by #1302
