### ISSUE TITLE
LVT slow compiling with gfortran 7.3

### ISSUE THREAD

**Issue by emkemp** [NASA-LIS/LISF#132]
The gfortran 7.3 compiler (used with the lis_7_gcc_7_3 private module on Discover) hangs in lvt/core/LVT_statsDataMod.F90, even with optimization turned off.

**Comment by emkemp** [comment]
lvt/core/LVT_statsDataMod.F90 hangs for over an hour when -O2 is used with gfortran.

**Comment by emkemp** [comment]
Likewise for -O1.

**Comment by jvgeiger** [comment]
It is worse than this.  gfortran requires more than 12 GB of RAM to compile this file (at least, I believe that it is this file).  Neither GNU version 7 nor version 8 can compile LVT on many systems due to insufficient memory.

I am testing with GNU version 9.

**Comment by jvgeiger** [comment]
The same behaviour occurs with GNU GCC (gcc and gfortran) version 9.  I am preparing a small example with a timing and memory usage report to send to the GNU GCC developers.

**Comment by jvgeiger** [comment]
Additional note, if you pull the individual LVT_statsEntry elements from the stats_struc derived data type, then the LVT_statsDataMod module compiles without issues.

**Comment by emkemp** [comment]
Update:  Jim opened a ticket with the GCC team about this problem -- see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91646

At this time the gfortran maintainers acknowledge this is a compiler bug, but have not determined a solution.

**Comment by dmocko** [comment]
This is still an issue with gcc-7.3 and -O1 optimization.  In fact, after 4+ hours, compilation is still hanging.  I don't see an update on the ticket opened with the GCC team.

My recommendation is that we see if this still occurs once we have a GCC environment on SLES12, as listed in Issue #490 .  Hopefully, a more recent version of GCC will not cause this problem.

We can keep this issue open until we have the SLES12 environment working.

**Comment by jvgeiger** [comment]
Sorry David.  I told you to use -O1.   You want to use -O0.  I just compiled LVT with GNU 7.3 using -O0, and the compilation completed in 20 minutes.

**Comment by dmocko** [comment]
Thanks for the info.  Compilation in ~20 minutes is about what LIS-7.1 would take, so no worries.  I confirm that -O0 did compile for me just now.

**Comment by bmcandr** [comment]
Merged into master in 5c3e8b9. Closing.
