### ISSUE TITLE
LIS does not compile with GNU (gcc and fortran)

### ISSUE THREAD

**Issue by jvgeiger** [NASA-LIS/LISF#135]
Compilation aborts in lis/routing/HYMAP2_router/HYMAP2_resopMod.F90

**Comment by jvgeiger** [comment]
There are additional compiling errors in:

dataassim/obs/NASA_SMAPsm/NASASMAPsm_Mod.F90
dataassim/obs/SMAP_NRTsm/SMAPNRTsm_Mod.F90
dataassim/obs/SMOPS_ASCATsm/SMOPS_ASCATsm_Mod.F90

**Comment by emkemp** [comment]
Fixed with pull request 141.
