### ISSUE TITLE
Potential divide by 0 error introduced in PR1179?

### ISSUE THREAD

**Issue by cmclaug2** [NASA-LIS/LISF#1381]
### Bug Description

On July 14th, I ran the testcase suite on the Main branch and a number of testcases crashed at line 4635 of LIS_historyMod.F90. 

In LIS_historyMod.F90, I manually changed "NF90_UNLIMITED" to "1" on line 2082, 2446, and 4632, recompiled, and reran the suite.  The tests that previously failed were now able to run. 

### Steps to replicate

e.g. clsmf25 testcase

Before fixing, I will run the failed tests using the lisf 7.5 modulefile. Above, the tests had failed using the intel19 modulefile

**Comment by jvgeiger** [comment]
I am running some tests myself.

**Comment by cmclaug2** [comment]
On the Main branch, I do not have any issue running the testcases using `LISF_7_5_INTEL_2021_4_0`.

The NetCDF-Fortran library in `LISF_7_INTEL_19_1_3_304` is `4.5.0_intel-19.1.0.166_sles12.3`.

The NetCDF-Fortran library in `LISF_7.5_INTEL_2021_4_0` is `4.8.1_intel-2021.4.0`.

I believe at some point `NF90_UNLIMITED` began support over the old dimension definition variable, `NF_UNLIMITED`.  It is possible `NF90_UNLIMITED` is not support in `4.5.0_intel-19.1.0.166_sles12.3`, and thus, not supported in `LISF_7_INTEL_19_1_3_304`.

I cannot find this specifc information in the [NetCDF-Fortran release notes](https://docs.unidata.ucar.edu/netcdf-c/current/RELEASE_NOTES.html), however, this hypothesis is consistent with the fact that all LISF uses of `NF90_UNLIMTED` occurred _after_ moving on from the `4.5.0_intel-19.1.0.166_sles12.3` library.

**Comment by cmclaug2** [comment]
`NF90_UNLIMITED` is acceptable syntax for the `len` parameter of `nc90_def_dim`.

To avoid problems, use the NetCDF-Fortran library 4.6.1 or greater.  These will be found in the latest modulefile. 

If you wish to use a modulefile that has a NetCDF-Fortran library that does not support `NF90_UNLIMITED`, replace all instances of `NF90_UNLIMITED` with a positive integer.
