### ISSUE TITLE
ISRIC soil texture assigns wrong index value for water in LDT

### ISSUE THREAD

**Issue by dmocko** [NASA-LIS/LISF#1406]
When choosing ISRIC soil textures in LDT, an incorrect index value will be assigned to water points.

The LDT ISRIC reader re-maps the soil textures from the source ISRIC datasets onto the STATSGO soil texture classification.

However, ISRIC assigns water points an index value of 13, while this value should be 14 for the STATSGO soil texture classification.

![ISRIC_water-points-issue_1](https://github.com/NASA-LIS/LISF/assets/38500701/136438c6-8540-4211-8dd6-6b049d80c614)
![ISRIC_water-points-issue_2](https://github.com/NASA-LIS/LISF/assets/38500701/17e87b66-72b5-4f0d-b7a6-9f2e4024c722)
![ISRIC_water-points-issue_3](https://github.com/NASA-LIS/LISF/assets/38500701/33e730d8-9db9-41e2-a5ab-38dd55b509c3)

Although this is a bug, it shouldn't greatly affect past simulations that used the ISRIC soil textures, as the affected points are very likely to be "water" points in the landcover classifications as well.  Still, users should check to ensure that this is true for their own individual past domains.

This bug revealed itself when running the MMF groundwater scheme in Noah-MP, which relies on soil textures even for water points.

Many thanks to @TimLahmers for identifying this issue.

**Comment by TimLahmers** [comment]
Thanks for submitting this @dmocko Please let us know when the PR to fix the bug is added. I will update my MMF branches and retest the code with this new fix when it is ready. That should be the final test needed before I submit the MMF PR.

**Comment by cmclaug2** [comment]
Resolved by #1407
