### ISSUE TITLE
Error with output printed out

### ISSUE THREAD

**Issue by mhle510** [NASA-LIS/LISF#1422]
Hello,

I use the template provided below to print out the [LIS output](https://github.com/NASA-LIS/LISF/blob/master/lis/configs/MODEL_OUTPUT_LIST.TBL.adoc).

For the variable [SoilMoist], when I enable it to be printed out, I need to change its unit from kg/m2 to m3/m3.

There are other variables I want to print out, but they cause the program to stop. These are:

- GPP
- snowT
- RootMoist
- Vapor_Pressure

Could you please double-check these output variables?

**Comment by dmocko** [comment]
Hi @mhle510 

Can you please attach your MODEL OUTPUT TBL file and the lislog file from your stopped program?
