### ISSUE TITLE
GDAS reader not working after 2019Jun12 data format change

### ISSUE THREAD

**Issue by dpsarmie** [NASA-LIS/LISF#159]
On 2019 June 12 12Z, NCEP upgraded the GDAS dataset by removing the two precipitation fields from the .f00 files. In addition, these f00 files were also changed to contain only instantaneous values and removed the time-averaged variables. 
These changes do not affect the final output that is generated by LIS (since the affected fields are taken from the f03 and f06 files), but it still causes the reader to fail as it is trying to read in the f00 files after 06/12/2019.

**Comment by dmocko** [comment]
For more on these changes, see this release announcement:
    https://www.weather.gov/media/notification/scn19-40gfs_v15_1.pdf
