### ISSUE TITLE
Add interface for create_lsm_output_filename in LDT for simGRACEJPLObs

### ISSUE THREAD

**Issue by emkemp** [NASA-LIS/LISF#166]
In ldt/DAobs/simGRACE_JPL/readsimGRACEJPLObs.F90, subroutine create_lsm_output_filename is called without an interface, and the subroutine is not in a module.  This is technically illegal because the subroutine call includes optional arguments, which require an interface.  (The subroutine is declared in ldt/DAobs/LISlsmSMobs/readLISlsmSMobs.F90.)

This bug was found when compiling LDT with ifort's -warn flag.

**Comment by bmcandr** [comment]
Fixed in #436.
