### ISSUE TITLE
Update documents in docs/LIS_users_guide

### ISSUE THREAD

**Issue by dmocko** [NASA-LIS/LISF#185]
Some files need updating in docs/LIS_users_guide

build.adoc - Update for Intel-18, and newest versions of HDF-5, Jasper; plus, add GDAL, ECCODES, FORTRANGis, libGEOTiff?

obtain-source.adoc - Remove subversion info and update for Github

testcases.adoc - Update testcases to remove support for old "public" testcases, and point to new end-to-end testcase

**Comment by karsenau** [comment]
I can checkout a branch and update the testcases.adoc file and commit.  Do we want to continue supporting information there for the internal test cases as well?
I will update the public test case information.

**Comment by dmocko** [comment]
Yes, we should still have the section with supporting information for the internal test cases.

However, it should be updated, primarily to specify that we don't distribute the output for these internal testcases, and that they are primarily for our internal regression testing.

Your commit so far looks great.  Can you please make another one with the above change?

After you do, I'll approve this pull request.

Thanks,

David

**Comment by karsenau** [comment]
Thanks for that feedback, and I agree with that.

Do you also want to keep the subsection of "Test-cases Input" for the internal tests?

**Comment by dmocko** [comment]
Looking closer at this file, probably everything starting with (and including) the following line, to the end of the document, should be deleted:
==== Test-cases LDT

The "==== The _testcases_ Sub-directory" section should be updated as above, and also perhaps mention that we don't distribute the input data either.  But, users can use the configs in this "testcases" sub-directory as a guide to setting up their own individual experiment.  However, the main purpose of this directory is for our internal testing.

**Comment by karsenau** [comment]
Just committed the latest updates based on your inputs.
Thanks!

**Comment by dmocko** [comment]
Approved the pull request to update the testcases.adoc file.

build.adoc and obtain-source.adoc still need to be updated.

**Comment by jvgeiger** [comment]
I am in the process of bringing in the LDT Users' Guide and the LVT Users' Guide.  I am bringing in the public 7.2 release version of these documents.   Then we can update them for our upcoming LISF 7.3 release.

For LIS
- [ ] Update build instructions (including libraries) (build.adoc)
- [ ] Update obtain-source.adoc
- [ ] Review all links
- [ ] Update/remove test cases section

For LDT
- [ ] Update build instructions (including libraries) (build.adoc)
- [ ] Update obtain-source.adoc
- [ ] Review all links
- [ ] Update/remove test cases section

For LVT
- [ ] Update build instructions (including libraries) (build.adoc)
- [ ] Update obtain-source.adoc
- [ ] Review all links
- [ ] Update/remove test cases section

**Comment by jvgeiger** [comment]
We must deliver updated documentation to 557WW, so we should be making our updates to the support/lisf-557ww-7.3 branch.

I will get Kristi's updates to testcases.adoc after I push the first pass at LDT and LVT users' guide.

**Comment by karsenau** [comment]
Thank you for the helpful checklist and update.

Just wanted to note -- 
 -- I updated the LDT testcase directories in the ldt code, so they should be ready to go, and
 -- there are no LVT testcases found in the lvt code. So the last bullet in your recent message can be removed.

**Comment by karsenau** [comment]
For documentation and testcase info updates, I can start committing  any future changes to the support/lisf-557ww-7.3 branch, if that is better for now.

**Comment by jvgeiger** [comment]
I updated the LDT, LIS, and LVT Users' Guides in the support/lisf-557ww-7.3 branch.  This branch has been merged into master.  I will first reconcile differences in the documented config files.  Then I will begin checking items off the above list.

**Comment by bmcandr** [comment]
Hi @jvgeiger @dmocko @karsenau,

Resurfacing this Issue thread tracking updates to the user guides. Are any of the boxes in the comment above ready to be checked off?

**Comment by karsenau** [comment]
Thanks for checking, bmcandr. 

I haven't contributing to updating the documentation in the past year but if there is anything you need help with towards updates and move to close this issue, I'm happy to help.

**Comment by bmcandr** [comment]
Thanks for the update @karsenau. Some of the items appear to be completed and I believe Jim is working on updating the docs so I'll let him check things off. Just wanted to bring this thread back up in the interest of cleaning out the Issue pile.

**Comment by jvgeiger** [comment]
I am working on these for the upcoming release.
