### ISSUE TITLE
Bug with dimension IDs in LVT_writevar_data_header

### ISSUE THREAD

**Issue by emkemp** [NASA-LIS/LISF#186]
The dimID array is only filled with valid values when LVT_writevar_data_header is first called to set the xlon and xlat variables.  In subsequent calls, random values are in the dimID array and are used when defining new variables to output to netCDF.

When Intel 18 compilers are used, the dimID values from the previous subroutine call are preserved.  However, this does not happen with GNU compilers.

A simple fix is to add the SAVE attribute to the variable declaration.

**Comment by dmocko** [comment]
Closed #186 with pull request #187
