### ISSUE TITLE
Remove obsolete URL links in the testcase README files

### ISSUE THREAD

**Issue by karsenau** [NASA-LIS/LISF#205]
Formerly, input dataset files were provided for the internal unit testcases. However, these testcases are only now being provided as LIS config examples for users to reference in their own setup.

Removal of this obsolete information from the README files should be made.

**Comment by karsenau** [comment]
Have pushed a couple of more commits for this issue and pull request that address the obsolete testcase files, which were updated and removal of former "wget" scripts.  

Also, removed the older "README_Discover" file in each software component.

**Comment by dmocko** [comment]
These changes look great.  About to approve the pull request.  Thanks.
