### ISSUE TITLE
LIS still writes statistics ASCII output even when turned off

### ISSUE THREAD

**Issue by dmocko** [NASA-LIS/LISF#384]
This lis.config entry is designed to turn off writing of ASCII statistics output in LIS:

Enable output statistics:               .false.

However, only when "netcdf" output data format is chosen, LIS will still write this output into a "fort.76" or similar file.  This file will only have statistics outputs by each variable, and not have any of the header lines (dates, columns, etc.).

The issue is in LIS_historyMod.F90, and the subroutine "writevar_netcdf_withstats_real".  This subroutine will "call stats" without checking the lis.config entry above.  Similar routines for GRIB or binary output instead "call write_stats", which does check the lis.config entry.

**Comment by emkemp** [comment]
Closing this issue since the pull request was merged in.
