### ISSUE TITLE
LDT bug when processing coarse resolution data 

### ISSUE THREAD

**Issue by sujayvkumar** [NASA-LIS/LISF#410]
When the LDT configuration involves the transformation of a coarse resolution data to a fine resolution target grid in curvilinear projection (lambert, for e.g.), the code seems to add artificial gaps along the boundary in the processed output. This is likely caused by the approach in LDT where the input data is first subset before interpolating and retrojecting to the fine resolution grid. The coarse resolution subset may not be sufficiently large to avoid causing gaps along the boundaries. When different interpolation options are on, different types of gaps are seen in the output.

**Comment by karsenau** [comment]
I will work on this and test for both Lambert and latlon domains.

**Comment by karsenau** [comment]
Update: 
Latest code modifications were successful in:

1)  adding a domain buffer to the target LIS grid for when subsetting parameters for Lambert projection - fixing the field gap issue;
2) fixed some issues encountered with latlon domains crossing the IDL; and
3) was able to exactly replicate a latlon CONUS domain with no changes to the output fields (at least for Noah parameters).

Will conduct a few more domain and projection tests prior to final push of the code updates.  Also, will prepare a testcase for these updated fixes.

**Comment by karsenau** [comment]
Note: Latest commit for this issue #410 relate only to the LDT part of the code. No similar updates made at this time to LIS.

**Comment by karsenau** [comment]
Quick update: Tested for an IDL-crossing domain with Lambert projection and all looks good.

**Comment by karsenau** [comment]
This issue should now be resolved with the latest code commits to the master branch (accepted).

**Comment by karsenau** [comment]
Add new buffer pixel options in the LDT config file to allow users to set the number of pixels in the x- and y-directions that add a buffer to the subsetted parameter target domain for transformations (e.g., from latlon to lambert grids).

**Comment by karsenau** [comment]
Final code is now committed and pull request made.

**Comment by karsenau** [comment]
New fix to LDT grid domains (Issue #410)

 This commit provides new updates to LDT in relation
  to the "buffer" outer domain option and support for domains
  that cross the International Dateline (IDL).

 - Resorted code to original lisdom_min|max calculations,
    which more correctly specifies outer domain required
    for curvilinear projections (e.g., Lambert);
 - Removed recently added code for these buffer and IDL domain
    issues, and replaced with simple code addition for when
    accounting for crossing the IDL.
 - Simplified the buffer code option and left the options in,
    however, they will not be triggered unless the user wants
    to turn them on. Default option is "off".
 - Made modifications to the LDT configs *adoc file.

 The new code was tested with a suite of six different test cases,
  which span continental US, global domain, and IDL domains, in both
  latlon and Lambert projections. All passed the checks and no
  buffer is required for any of the six cases.

 The new code has also been tested with SLES11/Intel18, GCC/Gfortran,
  SLES/Intel19 systems and all 6 test cases.

**Comment by emkemp** [comment]
Can this issue be closed?  The latest pull request fixes the lat/lon and Lambert Conformal cases in LDT.  Is that sufficient?

**Comment by karsenau** [comment]
Yes, the latest code update should address the concern that was initially reported in this issue ticket. Thank you.

**Comment by emkemp** [comment]
Okay, then I'm closing this issue.
