### ISSUE TITLE
Python scripts should support Python 3 [was: compile script does not work with python 3]

### ISSUE THREAD

**Issue by sujayvkumar** [NASA-LIS/LISF#432]
With python 3, I get the following error: 

-------------------------------------------------------------------
Compiling LIS version 7.2r...

[INFO] Compiling LIS source code

Makefile:26: Filepath: No such file or directory
Generating Filepath
rm -f *.o *.mod LIS *.d Filepath
./plugins.py
Traceback (most recent call last):
  File "./plugins.py", line 3, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
make: *** [Filepath] Error 1

[ERR] Compile failed

**Comment by emkemp** [comment]
An explanation:  The plugins.py script is written in Python 2, and Python 3 broke backward compatibility.  StringIO was removed from the Python standard library in 3.

That said, Python 2 officially dies (no further support) on 1 Jan 2020.  (See https://pythonclock.org/)  So all our Python scripts should be rewritten to conform to the new standard.

**Comment by jvgeiger** [comment]
Yes. I have already rewritten the compile scripts to use Python 3.  This did raise a weird Unicode-related error.  I plan to have this resolved for the public release.

**Comment by emkemp** [comment]
This has been fixed with pull request #475.  I am closing this issue.

**Comment by emkemp** [comment]
Actually, I will wait since the code changes are still on the support/lisf-557ww-7.3 branch.  We can close this once it migrates to master.
