### ISSUE TITLE
Obs attribute values not used by LIS

### ISSUE THREAD

**Issue by emkemp** [NASA-LIS/LISF#444]
The values in observation _attrib.txt files (e.g., snodep_attrib.txt) are not actually used by LIS DA.  Instead, the values of the files (observation name, max value, min value) are read in, temporarily stored in arrays (e.g., in lis/dataassim/obs/SNODEP/SNODEPobs_Mod.F90), and then deleted without being used or stored as ESMF state.

(Note:  This is not the case for _perturb_attrib.txt files; the data in these files are saved into ESMF State for use in DA.)

This implies the _attrib.txt files are unnecessary and should not even be read in.  Either they should be removed, or the LIS code should be changed to use the observation max/min attrib values.

**Comment by karsenau** [comment]
Sujay will have the final say on this comment/question, but I would believe we would want to keep this option of including the *_attrib.txt file for the DA Obs readers, as they should have access to the min/max information when reading and screening obs values.  That information isn't always needed on the ESMF state side of things for the DA algorithms.

**Comment by sujayvkumar** [comment]
As Kristi mentioned, the max/min values are available for imposing additional observational screening/thinning. In addition, internally, these attrib files are used to develop the ESMF containers for the model/obs state, perturbation, and increments vectors.
