### ISSUE TITLE
recent LDT updates fail on the NLDAS grid

### ISSUE THREAD

**Issue by sujayvkumar** [NASA-LIS/LISF#446]
It seems that the recent updates to LDT supporting a buffered grid while subsetting parameters leads to an error when working with the NLDAS grid and parameters. In this case, no buffering is required since the input parameters are in the same exact grid as the target grid. The error from LDT is: 

[ERR] The number of *subsetted* row or column points
           EXCEEDS the total *global* row or column points
           for the input parameter file, respectively.

   - The subsetted, global row points ::         234 >         224

   Please check your specified upper-right corner longitude and
    latitude extents, especially if you have entered a gridcell
    resolution that does not divide *nicely* into a 1-deg gridcell.
   Program stopping ...
 endrun is being called

**Comment by karsenau** [comment]
Thank you for reporting this issue. 
It appears this issue also can occur whenever a LIS domain is near the parameter file domain extents, but of different resolutions (not just in the NLDAS case).

Two options being considered at this time:
1) Implement a series of checks (e.g., resolution, projection, ...) within the routine, which currently checks and reports this error message in LDT (which you ran into), hoping we cover well all the different scenarios.

or 2) Add a new LDT config option that allows users to set a buffer or not, for each parameter type.

Also, if you have a test ldt.config with some of the NLDAS parameters that you are running, I can use that to test this issue.

**Comment by sujayvkumar** [comment]
Hi Kristi, 
I've placed a config file that gave me this problem at : /discover/nobackup/svkumar/share/4kristi

**Comment by karsenau** [comment]
Thanks - looking at it now.

**Comment by karsenau** [comment]
Just committed code update and pull request for this issue  #447 

Testcase files can be found here:
/discover/nobackup/projects/lis/Projects/LDT/LISF_Testcases/LDTDomain_Buffer/NLDAS

**Comment by emkemp** [comment]
I found a problem with the test case when running ldt.config_noahmp.nldasgrid_all.  I will document this on the pull request page.

**Comment by karsenau** [comment]
Just made a new commit to this Fix to this #447 issue ticket. 

I have tested with both Intel-18 and GCC compilers, with strict checks (-2 option) turned on. I was able to correct the issue and get the same results with both compiler versions.

You can use the same testcase as mentioned before, and the same LDT config file:
ldt.config_noahmp.nldasgrid_all

Please let me know if you need any other information or have any other questions/issues.
Thanks!

**Comment by emkemp** [comment]
The pull request has been merged in.  I'm closing this issue.
