### ISSUE TITLE
Change Noah-MP 3.6 irrigation rate to be constant over irrigation window

### ISSUE THREAD

**Issue by jerlingi** [NASA-LIS/LISF#464]
The current irrigation code in Noah-MP 3.6 checks the moisture availability threshold every integration time step. The proposed change will return to a single check of the soil column at the beginning of the irrigation window and will result in a constant rate applied for the entire irrigation window.

**Comment by emkemp** [comment]
This was fixed by pull request #469.  I am closing the issue.
