### ISSUE TITLE
Document "AGRMET GALWEM nominal resolution (km):"

### ISSUE THREAD

**Issue by jvgeiger** [NASA-LIS/LISF#466]
We need to add documentation for "AGRMET GALWEM nominal resolution (km):".

**Comment by emkemp** [comment]
This is addressed by pull request #474

**Comment by emkemp** [comment]
Pull request #474 was merged into support/lisf-557ww-7.3.  I will leave this issue open until the changes migrate into master.

**Comment by dmocko** [comment]
This change has been migrated into master, so I am going to close this issue.
