### ISSUE TITLE
Noah3.3 Sprinkler Irrigation Duration

### ISSUE THREAD

**Issue by jerlingi** [NASA-LIS/LISF#468]
Noah3.3 sprinkler irrigation only runs for the first integration time step after the trigger. A fix needs to be implemented so that the irrigation runs for the duration of irrhrs.

**Comment by bmcandr** [comment]
Hi @jerlingi,

Was this issue resolved in #469? If so, I will close out this issue.

**Comment by jerlingi** [comment]
Hi @bmcandr,

This was fixed by #469. Please close the issue.

Thanks!
