### ISSUE TITLE
The test for IMERG Late_V06B is broken

### ISSUE THREAD

**Issue by jvgeiger** [NASA-LIS/LISF#501]
The testcase contains files like 201905/3B-HHR-L.MS.MRG.3IMERG.20190530-S003000-E005959.0030.V06B.HDF5.

After  pull request #492,  LIS now tries to read files named 201905/3B-HHR-L.MS.MRG.3IMERG.20190530-S003000-E005959.0030.V06B.RT-H5.

Our project disk does not contain Late_V06B data for 201905.

@dpsarmie would you please retest and repackaged the IMERG Late_V06B testcase?

Thanks.

**Comment by dpsarmie** [comment]
Yes, I'll take care of it.

**Comment by jvgeiger** [comment]
Thanks!
