### ISSUE TITLE
Expand filename char length in some LIS forcing readers

### ISSUE THREAD

**Issue by karsenau** [NASA-LIS/LISF#533]
Reviewing some LIS forcing readers, it was found that some filename character lengths, which may include full directory path too, are less than 100 characters, causing some filenames to be truncated. When this happens, the log files may not always inform the user of this issue.

Plan to go through LIS (and LDT) forcing readers that are mostly used and expand the filename lengths.

Here is the current list:
cmorph/get_cmorph.F90:  character(len=99) :: filename ! Filename variables for precip data sources
imerg/get_imerg.F90:  character(len=99) :: filename ! Filename variables for precip data sources
pet_usgs/get_petusgs.F90:  character(99) :: filename              ! Filename variables for PET data sources

3B42V6/get_TRMM3B42V6.F90:  character(len=80) :: name ! Filename variables for precip data sources
3B42V7/get_TRMM3B42V7.F90:  character(len=80) :: filename     ! Filename variables for precip data sources
3B42V7/get_TRMM3B42V7.F90:  character(80)       :: filename
AWAP/get_AWAP.F90:    character(80) :: file_name       ! Filename variables for precip data sources
cmap/get_cmap.F90:  character*80 :: filename ! Filename variables for precip data sources
cmap/get_cmap.F90:  read(UNIT=temp, fmt='(a80)') filename
cmap/get_cmap.F90:  read(UNIT=temp, fmt='(a80)') filename
RFE2Daily/get_RFE2Daily.F90:  character*80 :: filename    ! Filename variables for precip data sources
stg2/get_stg2.F90:    character(80) :: file_name      ! Filename variables for precip data sources
stg4/get_stg4.F90:    character(80) :: file_name       ! Filename variables for precip data sources
WRFout/get_WRFout.F90:   character*80, intent(out) :: filename

**Comment by dmocko** [comment]
Hi Kristi,
Thanks for raising this issue again.  We have Issue #371 already open.
David

**Comment by karsenau** [comment]
Hi David,

Thanks for pointing out that other existing ticket. I may go ahead and complete this quick task and address this more immediate issue, as some of the readers that folks are currently using is not alerting me of the file length issue.

I think what is proposed for issue #371 issue sounds like a great idea to update our existing forcing and obs readers and making that a practice going forward.
