### ISSUE TITLE
Develop the capability for restart transformations across different domains

### ISSUE THREAD

**Issue by sujayvkumar** [NASA-LIS/LISF#576]
Use the restart file from a larger domain to develop a restart file for a smaller domain

**Comment by agetiran** [comment]
This is great! Does it include a rescaling capability as well?

**Comment by sujayvkumar** [comment]
What do you mean by 'rescaling'? The current capability essentially interpolates the restart between two domains.

**Comment by agetiran** [comment]
So, we should be able to go from a spatial resolution to another?

**Comment by sujayvkumar** [comment]
yes, absolutely.
