### ISSUE TITLE
read_gefs_reforecast.F90 does not compile when ecCodes is disabled

### ISSUE THREAD

**Issue by jvgeiger** [NASA-LIS/LISF#587]
In particular, this else block

```
374   else
375      write(LIS_logunit,*) &
376        '[ERR] Could not find file: ',trim(filename)
377      ferror = 0
378   endif
```

is outside of the ```#if(defined USE_GRIBAPI) / #endif``` pair that contains the corresponding if statement.

**Comment by karsenau** [comment]
Please let me know if would like for me to fix this issue.

Thanks!
