### ISSUE TITLE
GRACE DA not working properly with Noah_MP

### ISSUE THREAD

**Issue by bailinglee** [NASA-LIS/LISF#61]
There are a few things related to this issue:
1) some code changes made by Wanshu Nie in NoahMP36_readrst.F90 were not checked into the master branch.   
2) The minimal smc threshold is hard coded in noahmp36_settws.F90 while the min and max values provided in the perturbation attribute file and retrieved in noahmp36_qctws.F90 are not being used.
3)These is no qc check for smc2, smc3, and smc4 in noahmp36_qctws.F90.

**Comment by bailinglee** [comment]
I have the fixed files in feature/grace_da_noahmp.3.6.  LDT was also modified to ingest 0.25  degree GRACE data.  I'd like to check these changes into the master but don't know how to create a pull request. Maybe I don't have the role to do that?

**Comment by emkemp** [comment]
Hi Bailing:

I just looked at your feature/grace_da_noahmp3.6 branch, and it appears to be identical to the master branch on NASA-LIS.  Did you remember to push your changes from Discover to GitHub?

**Comment by bailinglee** [comment]
Hi Eric,
   I did using this command:
git push -u origin feature/grace_da_noahmp.3.6

Bailing

**Comment by emkemp** [comment]
Will you be in the office today?  This looks like a "sit down together" issue.

**Comment by bailinglee** [comment]
No. I will be in tomorrow.

**Comment by emkemp** [comment]
Okay, can we meet Wednesday afternoon to figure this out?

**Comment by bailinglee** [comment]
Sure.  I am free all day tomorrow.
