### ISSUE TITLE
LIS-JULES does not update LIS_snow_struc

### ISSUE THREAD

**Issue by emkemp** [NASA-LIS/LISF#623]
The AGRMET Ops runmode uses LIS_snow_struc to pull (ensemble-averaged) tile values of snow depth and SWE for a couple of calculations.  But the values in this structure (defined in lis/core/LIS_snowMod.F90) are not filled when JULES is run.

An example of proper updates of this structure is LIS-Noah 3.9.  Please see:

lis/surfacemodels/land/noah.3.9/noah39_dynsetup.F90
lis/surfacemodels/land/noah.3.9/da_snodep/noah39_setsnodepvars.F90
lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_setusafsivars.F90

A patch needs to be implemented for LIS 7.3.

**Comment by bmcandr** [comment]
@emkemp, looks like this one was resolved in #633.

**Comment by emkemp** [comment]
This was probably fixed, but in any case 557 WW is no longer using JULES.  So this issue is moot.
