### ISSUE TITLE
LIS-NoahMP 4.0.1 does not update LIS_snow_struc

### ISSUE THREAD

**Issue by emkemp** [NASA-LIS/LISF#624]
The AGRMET Ops runmode uses LIS_snow_struc to pull (ensemble-averaged) tile values of snow depth and SWE for a couple of calculations. But the values in this structure (defined in lis/core/LIS_snowMod.F90) are not filled when NoahMP4.0.1 is run.

An example of proper updates of this structure is LIS-Noah 3.9. Please see:

lis/surfacemodels/land/noah.3.9/noah39_dynsetup.F90
lis/surfacemodels/land/noah.3.9/da_snodep/noah39_setsnodepvars.F90
lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_setusafsivars.F90

A patch needs to be implemented for LIS 7.3.

**Comment by bmcandr** [comment]
Hi @emkemp, looks like you resolved this in #634. Can we link and close out this issue?

**Comment by emkemp** [comment]
This was fixed.  Closing.
