### ISSUE TITLE
LDT Documentation for Running Mode

### ISSUE THREAD

**Issue by jerlingi** [NASA-LIS/LISF#712]
In the LDT User's Guide, some of the options for "LDT running mode:" appear to be out-of-date. For example, “Restart preprocessing” is no longer valid option, and "Climatological restart processing" does not appear.

**Comment by karsenau** [comment]
Hi @jerlingi,

Thank you for catching these out-of-date options and what may be missing.  Please let us know if you would like any help with those updates or if you would like to add and update the entries.

**Comment by jerlingi** [comment]
After review, we were missing the "NUWRF preprocessing for real," "ANN processing," and "LISHydro preprocessing for WRFHydro" options, which were in plugins/LDT_pluginIndices.F90 but not ldt.config.adoc. "Climatological restart processing" was documented as "Restart preprocessing." 

It might be a good idea for the developers of these options to make sure all of the running options made it into the documentation.

**Comment by bmcandr** [comment]
Merged into master in 5c3e8b9
