### ISSUE TITLE
Fix output of RMSE sample size counts in LVT

### ISSUE THREAD

**Issue by emkemp** [NASA-LIS/LISF#735]
### Bug Description

Before writing the sample sizes for the RMSE calculation, LVT will copy the data to a temporary array.  See lvt/metrics/LVT_RMSEMod.F90, subroutine LVT_writeMetric_RMSE.  Due to a typo, the temporary array is overwritten with data for a different metric:

                         value_total(:,m) = &
                              stats%rmse(m)%value_total(:,k,l)
                         count_value_total(:,m) = & 
                              stats%rmse(m)%count_value_total(:,k,l)
                         Value_ci(m) = stats%rmse(m)%value_ci(k,l)

                         value_stdev_total(:,m) = &
                              stats%rmse(m)%value_stdev_total(:,k,l)
                         count_value_total(:,m) = &   ! <-- EMK This is wrong
                              stats%rmse(m)%count_value_stdev_total(:,k,l)

Worse, the STDEV calculation is not supported in LVT restart files.  Together, if LVT is restarted, the sample size counts for RMSE will be smaller than they should be.

**Comment by bmcandr** [comment]
I tested with a testcase from an old PR and output looks good. I'll go ahead and merge.

**Comment by bmcandr** [comment]
Merged into master in 5c3e8b9
