### ISSUE TITLE
Update lisf_7_intel_19_1_3_304 custom module file for ESMF 8.0.1

### ISSUE THREAD

**Issue by jvgeiger** [NASA-LIS/LISF#785]
Update lisf_7_intel_19_1_3_304 custom module file for skylake on discover

**Comment by jvgeiger** [comment]
This updates the lisf_7_intel_19_1_3_304 custom modulefile to use ESMF 8.0.1 and updates to Intel MPI 19.1.3.304.

**Comment by bmcandr** [comment]
Merged into master in aac4db0
