### ISSUE TITLE
Add irrigation interfaces in Noah-MP

### ISSUE THREAD

**Issue by sujayvkumar** [NASA-LIS/LISF#8]

**Comment by jerlingi** [comment]
Including updates outlined in W. Nie et al. (2018) (https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1029/2017WR022178) with the ability to toggle the groundwater abstraction on and off.

**Comment by dmocko** [comment]
Can this issue now be closed?

**Comment by dmocko** [comment]
Closing this issue.  Interfaces were added via pull request #150
