### ISSUE TITLE
compilation error for LISF_557WW_release_7.4.2 with JULES.5.0 

### ISSUE THREAD

**Issue by hashmifatima** [NASA-LIS/LISF#809]
[configure.docx](https://github.com/NASA-LIS/LISF/files/6647381/configure.docx)
[liscompile.docx](https://github.com/NASA-LIS/LISF/files/6647382/liscompile.docx)
@jvgeiger @jerrywegiel 

### Bug Description

I am installing LISF_557WW_release_7.4.2  with JULES.5.0.
Earlier we used to copy src and utils directories from JULES.5.0 (downloaded from UK met office). Now it is already there and program inside utils directory are different than the earlier one. During compilation I am getting this error message:

../surfacemodels/land/jules.5.0/utils/mpi_dummy/mpi_mod.F90(438): error #7111: An interface-body is incorrectly positioned within a program unit.
interface mpi_bcast
----------^
compilation aborted for ../surfacemodels/land/jules.5.0/utils/mpi_dummy/mpi_mod.F90 (code 1)
Makefile:139: recipe for target 'mpi_mod.o' failed
make: *** [mpi_mod.o] Error 1

[ERR] Compile failed

### Steps to Replicate

Replace this text with instructions for replicating this bug.

**Comment by jvgeiger** [comment]
This is being discussed on ModelingGuru.  See https://modelingguru.nasa.gov/message/11027
