### ISSUE TITLE
Working With GitHub doc in support/lisf-public-7.3 is out of date

### ISSUE THREAD

**Issue by emkemp** [NASA-LIS/LISF#874]
The Working With Github document in support/lisf-public-7.3 has not been updated since 4 Dec 2020.  In particular, the git commands for interfacing with github are still using the https syntax, which will stop working in mid-August 2021.  Recommend copying the latest version in master to this public branch.

**Comment by bmcandr** [comment]
Looking back, I probably should have targeted support/lisf-public-7.3 when adding the SSH key section. I have copied over the contents of `working_with_github/` to a feature branch ready for a PR to bring the support branch version up to date. 

@jvgeiger do you approve of this maneuver?

**Comment by dmocko** [comment]
Hi @bmcandr - thanks for making sure the public support version is up to date.

I will let @jvgeiger respond to the best way to do this.

But I do have a request/question.  In Section 4.3.3, there are two examples of:

git clone https://github.com/NASA-LIS/LISF.git

Should that instead be?:

git clone https://github.com/<username>/LISF.git

(or something similar?  There are a couple different ways to represent "username" in this document).

**Comment by dmocko** [comment]
I edited my post above because putting username in the .lt. and .gt. brackets hid the word username.
