### ISSUE TITLE
LDT HYMAP parameters for global domain

### ISSUE THREAD

**Issue by hkato1** [NASA-LIS/LISF#886]
### Bug Description

Missing values are found in adjacent grid boxes along 180W longitude when we create HYMAP parameters in LDT causing the HYMAP routing outputs having missing values in the global domain simulations.
![image](https://user-images.githubusercontent.com/7863635/130658230-be67c9ff-551a-4bd2-acf2-2f6bf75ec5a1.png)

### Steps to Replicate

Run LDT for "LSM parameter processing" with Routing Model "HYMAP" for global domain at 0.25 degree and 1 degree.

 hkato1

**Comment by bmcandr** [comment]
Merged to master in 788c8f8.
