### ISSUE TITLE
Add diagnostic checks in LVT  ISMN soil moisture reader when soil profile interpolation provides zero weights

### ISSUE THREAD

**Issue by sujayvkumar** [NASA-LIS/LISF#95]

**Comment by dmocko** [comment]
This code was updated: lvt/interp/compute_vinterp_weights.F90

Does that mean that previous analysis with other soil moisture datasets (SCAN, etc.) are affected as well?

Is the surface soil moisture analysis affected, or just levels below the surface?

**Comment by sujayvkumar** [comment]
I do not expect any changes to the interpolation weights except it screens out zero weights that are output.
-S

=========================================
Sujay Kumar, Ph.D.
Research Physical Scientist
Hydrological Sciences Laboratory
Code 617, Bldg 33, Rm G219
Ph: 301-286-8663
Sujay.V.Kumar@nasa.gov<mailto:Sujay.V.Kumar@nasa.gov>
http://neptune.gsfc.nasa.gov/hsb/personnel/index.php?id=170
=========================================
